name: Configs tests

on: [pull_request, push]
jobs:
  test_all_profiles:
    runs-on: ubuntu-latest
    name: Check if all profiles are tested
    steps:
      - uses: actions/checkout@v1
      - run: python bin/cchecker.py

  profile_test:
    name: Run ${{ matrix.profile }} profile
    needs: test_all_profiles
    runs-on: ubuntu-latest
    strategy:
        matrix:
          profile:
            - awsbatch
            - bi
            - bigpurple
            - binac
            - cbe
            - ccga_dx
            - ccga_med
            - cfc
            - cfc_dev
            - crick
            - denbi_qbic
            - ebc
            - genotoul
            - genouest
            - gis
            - google
            - hebbe
            - icr_davros
            - kraken
            - munin
            - pasteur
            - phoenix
            - prince
            - shh
            - tacc_ls5
            - uct_hex
            - uppmax
            - utd_ganymede
            - uzh
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Check ${{ matrix.profile }} profile
        env:
          SCRATCH: '~'
          NXF_GLOBAL_CONFIG: awsbatch.config
        run: nextflow run ${GITHUB_WORKSPACE}/configtest.nf -profile ${{ matrix.profile }} --custom_config_base=${GITHUB_WORKSPACE}
